### ISSUE TITLE
Damage error

### ISSUE THREAD

**Issue by TemhemKaya** [suriyun-production/battle-io-docs#62] opened 2022-11-06 12:22 UTC
Hi,
Other users entering the room do no damage. What could be the problem

**Comment by TemhemKaya** [comment] 2022-11-07 11:43
Please help me @insthync

**Comment by Salja** [comment] 2022-12-16 07:56
I got Same issue Sometimes the room owner i think or master Client dont get damage you can Hit him but Not alltime He get damage pls Take a Look at it

**Comment by Salja** [comment] 2022-12-20 13:27
@insthync can you pls take a look it looks sometimes you play "Hit Effect" but dont make any damage

**Comment by insthync** [comment] 2022-12-20 14:22
So the problem is it not taking damage **sometime**, not everytime, right?

**Comment by Salja** [comment] 2022-12-20 17:06
for me its like this exaple; they run behind a player and they hit him with the sword sometimes it happens that it shows a hit effect but the player doesn't get any damage, sometimes it's very common and it's very annoying, it's happened that you get this very often in a row had problem

also i try to make a video

**Comment by Salja** [comment] 2022-12-20 17:18
ok here i reproduce it 

i create a room with dteahmatch rules and no bots
i join with a 2 client the room and make ready check
start the game with the room owner client

i leave then the game with "Room Owner"
i rejoin the game with "Old Room Owner"

i go with the "Old Room Owner" to the other Client
i run around and attack him

you can see at the left client window sometimes you get the "Hit Effect" but only at the left window the other client at the right window dont display the "Hit Effect"

its really really bad bc ppl think he hit him and then he think the other cheat bc he dont get damage but the "Hit Effect" shows what he get damage

https://youtu.be/vobcqNEOb08

**Comment by Salja** [comment] 2022-12-21 20:59
any new here ? @insthync

**Comment by insthync** [comment] 2022-12-22 04:42
Have to change damage applying workflow, now it is proceeding by server only, so when it hit at client and play "Hit Effect" but it doesn't hit at server then the damage won't be applied, so I have to change it by allowing clients to tell the server that the damage is hit.

**Comment by Salja** [comment] 2022-12-22 04:44
Sounds good what you know what is the Problem will BE nice If you have Something to Post again Here only the needed Changes 

Thanks you very much for helping

**Comment by Salja** [comment] 2022-12-23 21:00
It Looks Like more Problems comes its alltime with the room creator for example i try the health function at Player Controller IT works for the room creator bur Not for the other Players at all Same for damage Most issues you can See If you Open a room and play

**Comment by Salja** [comment] 2022-12-28 20:54
Any news here about the issue ? its really bad issue bc its not really playable at the moment

@insthync

**Comment by insthync** [comment] 2022-12-28 23:12
@Salja Health function will works for room creators only to reduce hacking.

Not sure that you use Battle IO or Shooter IO, but I made changes to damage applying which you can see the changes from 

https://github.com/insthync/photon-shooter-io-core/commits/master
https://github.com/insthync/photon-battle-io-core/commits/master

**Comment by Salja** [comment] 2023-01-17 18:31
can close its fixed thanks

**Closed as completed** 2023-01-18 04:11 UTC
